version: '3'
services:
  nginx:
    image: nginx
    container_name: movietoar
    ports: 
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./html:/usr/share/nginx/html/html
